# Generated by Django 5.1.1 on 2024-11-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="item",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.AddField(
            model_name="purchase",
            name="quantity_sold",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
        migrations.CreateModel(
            name="PurchasedItemDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashier.inventoryitem",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashier.purchase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchase",
            name="items",
            field=models.ManyToManyField(
                through="cashier.PurchasedItemDetails", to="cashier.inventoryitem"
            ),
        ),
    ]
