# Generated by Django 5.1.1 on 2024-11-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0002_remove_purchase_item_remove_purchase_quantity_and_more"),
        ("prescriptions", "0009_prescription_picked_up_alter_prescription_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="prescriptions",
            field=models.ManyToManyField(to="prescriptions.prescription"),
        ),
    ]
