# Generated by Django 5.1.1 on 2024-11-21 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pharmacy_address',
            field=models.TextField(default='123 Main Street, Anytown, USA'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pharmacy_name',
            field=models.CharField(default='Pharmacy Awesome', max_length=255),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pharmacy_phone',
            field=models.CharField(default='(123) 456-7890', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
