# Generated by Django 5.1.1 on 2024-11-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_receipt_pharmacy_address_receipt_pharmacy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
