# Generated by Django 5.1.3 on 2024-11-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_purchase_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='pharmacy_address',
            field=models.TextField(default='1209 E 2nd St #100'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pharmacy_phone',
            field=models.CharField(default='(520) 855-3010', max_length=20),
        ),
    ]
