# Generated by Django 5.1.3 on 2024-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_alter_receipt_pharmacy_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='signature_image',
            field=models.ImageField(default=0, upload_to='signatures/'),
            preserve_default=False,
        ),
    ]
