# Generated by Django 5.1.1 on 2024-11-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0010_alter_receipt_transaction_date"),
        ("prescriptions", "0010_prescription_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="prescriptions",
        ),
        migrations.CreateModel(
            name="PurchasedPrescriptionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "prescription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.prescription",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashier.purchase",
                    ),
                ),
            ],
        ),
    ]
