# Generated by Django 5.1.1 on 2024-11-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0011_remove_purchase_prescriptions_and_more"),
        ("prescriptions", "0010_prescription_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="prescriptions",
            field=models.ManyToManyField(
                through="cashier.PurchasedPrescriptionDetails",
                to="prescriptions.prescription",
            ),
        ),
    ]
