# Generated by Django 5.1.1 on 2024-11-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0012_purchase_prescriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedprescriptiondetails",
            name="quantity",
        ),
    ]
