# Generated by Django 5.1.1 on 2024-11-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0009_alter_purchase_signature_image"),
        ("cashier", "0013_remove_purchasedprescriptiondetails_quantity"),
    ]

    operations = []
