# Generated by Django 5.1.2 on 2025-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_merge_20241124_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
