# Generated by Django 5.1.1 on 2024-10-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_attempts',
        ),
    ]
