# Generated by Django 5.1.1 on 2024-10-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lockout_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
