# Generated by Django 5.1.1 on 2024-10-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
