# Generated by Django 5.1.1 on 2024-10-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
