# Generated by Django 5.1.1 on 2024-10-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_inventory', '0003_stock_delete_medication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
