# Generated by Django 5.1.1 on 2024-11-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_inventory', '0008_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='stock_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
