# Generated by Django 5.0.1 on 2024-10-11 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
