# Generated by Django 5.1.1 on 2024-10-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0001_initial"),
        ("patient", "0001_initial"),
        (
            "prescriptions",
            "0003_remove_prescription_expiry_remove_prescription_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="medication_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="prescription",
            name="medication",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="drugs.drug"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
    ]
