# Generated by Django 5.1.1 on 2024-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0006_alter_prescription_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="in_person",
            field=models.BooleanField(default=False),
        ),
    ]
