# Generated by Django 5.1.2 on 2024-11-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescription_in_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
