# Generated by Django 5.1.1 on 2024-11-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
        ("prescriptions", "0008_prescription_is_filled"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="picked_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="patient.patient",
            ),
        ),
    ]
