# Generated by Django 5.1.1 on 2024-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0009_prescription_picked_up_alter_prescription_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
