# Generated by Django 5.1.1 on 2024-10-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
