# Generated by Django 5.1.1 on 2024-10-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage_form', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=255)),
                ('drug_class', models.CharField(max_length=100)),
                ('indications', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('contraind', models.TextField(blank=True, null=True)),
                ('dosage_inst', models.TextField(blank=True, null=True)),
                ('stock_qty', models.PositiveIntegerField()),
                ('exp_date', models.DateField()),
                ('rx_required', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_cond', models.TextField(blank=True, null=True)),
                ('bar_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
