# Generated by Django 5.1.1 on 2024-10-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Ointment', 'Ointment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_class',
            field=models.CharField(choices=[('Analgesics', 'Analgesics'), ('Antibiotics', 'Antibiotics'), ('Antivirals', 'Antivirals'), ('Antidepressants', 'Antidepressants'), ('Antihypertensives', 'Antihypertensives'), ('Antihistamines', 'Antihistamines'), ('Anticoagulants', 'Anticoagulants'), ('Diuretics', 'Diuretics'), ('Hormonal agents', 'Hormonal agents'), ('Statins', 'Statins'), ('Beta-blockers', 'Beta-blockers'), ('Corticosteroids', 'Corticosteroids'), ('Mood stabilizers', 'Mood stabilizers'), ('Antipsychotics', 'Antipsychotics'), ('Immunosuppressants', 'Immunosuppressants')], max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='rx_required',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.PositiveIntegerField(),
        ),
    ]
