# Generated by Django 5.1.1 on 2024-10-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescriptionlog',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
