# Generated by Django 5.1.1 on 2024-10-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_prescriptionlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlog',
            name='drug_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionlog',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
