# Generated by Django 5.1.1 on 2024-11-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_alter_prescriptionlog_drug_type_and_more"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptionlog",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="prescriptionlog",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
    ]
