# Generated by Django 5.1.2 on 2024-11-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_prescriptionlog_pharmacist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('deleted', 'Drug Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
