# Generated by Django 5.1.1 on 2024-11-23 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_loginlogoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlogoutlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='loginlogoutlog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginlogoutlog',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
