# Generated by Django 5.1.1 on 2024-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_remove_loginlogoutlog_timestamp_loginlogoutlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogoutlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'login'), ('logout', 'logout')], max_length=10),
        ),
    ]
