# Generated by Django 5.1.1 on 2024-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_loginlogoutlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogoutlog',
            name='failed_login',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loginlogoutlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'login'), ('logout', 'logout'), ('failed', 'login fail')], max_length=10),
        ),
    ]
