# Generated by Django 5.1.1 on 2024-11-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_accountactivitylog_delete_loginlogoutlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivitylog',
            name='event_type',
            field=models.CharField(choices=[('login', 'login'), ('logout', 'logout'), ('failed', 'failed'), ('locked', 'locked'), ('unlocked', 'unlocked')], max_length=10),
        ),
    ]
