# Generated by Django 5.1.1 on 2024-11-23 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_stock_qty'),
        ('logs', '0015_alter_inventorylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivitylog',
            name='failed_login',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_reason',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.CreateModel(
            name='DrugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=42, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
    ]
