# Generated by Django 5.1.1 on 2024-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0018_alter_inventorylog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
